#!/usr/bin/env bash

mkdir -p logs

echo "Starting Discovery"
java -jar ServiceDiscovery/target/ServiceDiscovery-0.0.1-SNAPSHOT.jar > logs/discovery.log 2>&1 &
DISCOVERY_PID=$!

echo "Starting Gateway..."
java -jar APIGateway/target/APIGateway-0.0.1-SNAPSHOT.jar > logs/gateway.log 2>&1 &
GATEWAY_PID=$!

echo "Starting User MicroService..."
java -jar UserMicroService/target/UserMicroService-0.0.1-SNAPSHOT.jar  > logs/UserMicroService.log 2>&1 &
UserMicroService=$!

echo "All services started."

trap "kill 0; exit" INT

wait
