spring:
  application:
    name: AUTH-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://mysql:3306/users
    username: root
    password: root

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka